### ISSUE TITLE
Request Update "mutexes"

### ISSUE THREAD

**Issue by Schezuk** [gobyexample-cn/gobyexample#39]
Page https://gobyexample.com/mutexes is Updated on Fri, 09 Feb 2018.

**Comment by gorda** [comment]
@Schezuk 您好，感谢你告知了我们 `mutexes` 例子的内容有更新。

事实上，目前该项目已经重新开始维护，我们准备近期同步更新整个项目（当然也包括这个例子），如果你对此感兴趣的话，非常欢迎你能帮我们同步部分例子，或继续帮我们指出错误的地方。
