### ISSUE TITLE
Request Correction "stateful-goroutines"

### ISSUE THREAD

**Issue by Schezuk** [gobyexample-cn/gobyexample#40]
Variable "opsFinal" is obsolete.

**Comment by gorda** [comment]
@Schezuk 您好，我不是很明白你的问题，你可能需要更详细的描述一下该问题。

鉴于该 issue 已经提出一年多，你可能已经解决该问题，我会保留这个 issue 几天，在此期间，如果你没有回复的话，之后我会关闭它。
