### ISSUE TITLE
执行结果与网页上不一致啊

### ISSUE THREAD

**Issue by chuanqiangTsang** [gobyexample-cn/gobyexample#47]
我把代码直接贴上去运行  结果跟网页上的结果不一致

新人学习  求解析

**Comment by gorda** [comment]
@chuanqiangTsang 这可能需要你贴出具体的代码，我们才能帮你分析。鉴于该 issue 已经提出一年多，你可能已经解决该问题，我会保留这个 issue 几天，在此期间，如果你没有回复的话，之后我会关闭它。
