### ISSUE TITLE
slices翻译有误

### ISSUE THREAD

**Issue by cui-cjm** [gobyexample-cn/gobyexample#48]
https://books.studygolang.com/gobyexample/slices/

This slices up to (but excluding) s[5].
网页端错误翻译：这个 slice 从 s[0] 到（但是**_### 包含_**）s[5]。
正确翻译：这个 slice 从 s[0] 到（但是排除）s[5]。

**Comment by gorda** [comment]
@cui-cjm 感谢你提出的问题，我们维护项目的访问地址是 [https://gobyexample-cn.github.io/slices](https://gobyexample-cn.github.io/slices)，我们网站的内容看起来似乎是正确的。

如果您还有其它问题，欢迎随时告诉我们
