### ISSUE TITLE
非阻塞通道操作示例的结果有点问题

### ISSUE THREAD

**Issue by winston-ke** [gobyexample-cn/gobyexample#55]

**Comment by gorda** [comment]
@winston-ke 可以再描述得详细一点吗？我试着运行了这个示例，输出结果似乎没有问题。代码以及运行结果可以在[这里](https://play.golang.org/p/1RE4ZFcdmxR)在线查看

![image](https://user-images.githubusercontent.com/32058002/77067978-caac2b00-6a20-11ea-9aa8-c3315c6cfaa0.png)
