### ISSUE TITLE
methods模块下翻译有误

### ISSUE THREAD

**Issue by hiwangzheng** [gobyexample-cn/gobyexample#57]
原文
![image](https://user-images.githubusercontent.com/25281349/77889087-dd83f280-729f-11ea-96cd-f9f26e829d79.png)

翻译
![image](https://user-images.githubusercontent.com/25281349/77889122-f1c7ef80-729f-11ea-9ea0-b06a232c045d.png)

推荐翻译：这里的area方法有一个 *rect 类型的接收器(receiver)

**Comment by hiwangzheng** [comment]
或者: 这里的area是一个拥有 *rect 类型接收器(receiver)的方法。

**Comment by hiwangzheng** [comment]
或者: 这里的area是一个拥有 *rect 类型接收器(receiver)的方法。
这样是否会更贴切？毕竟没有接收器的叫函数，有接收器的叫方法。

**Comment by gorda** [comment]
> 或者: 这里的area是一个拥有 *rect 类型接收器(receiver)的方法。
> 这样是否会更贴切？毕竟没有接收器的叫函数，有接收器的叫方法。

@hiwangzheng 感谢指正，你方便提个 pr 吗，如果不方便的话，我就直接改了

**Comment by hiwangzheng** [comment]
> > 或者: 这里的area是一个拥有 *rect 类型接收器(receiver)的方法。
> > 这样是否会更贴切？毕竟没有接收器的叫函数，有接收器的叫方法。
> 
> @hiwangzheng 感谢指正，你方便提个 pr 吗，如果不方便的话，我就直接改了

已提交pull request。

**Comment by gorda** [comment]
感谢共享，已合并！

![image](https://user-images.githubusercontent.com/32058002/78046605-f082e980-73a9-11ea-8bba-0491af1fe4bc.png)
