### ISSUE TITLE
语法问题

### ISSUE THREAD

**Issue by fcdml** [gobyexample-cn/gobyexample#69]
![image](https://user-images.githubusercontent.com/17615663/96325622-c2ba7500-105b-11eb-8a06-c458bb5043c6.png)
这里不包含下标为5的元素  **在切片那一页**
![image](https://user-images.githubusercontent.com/17615663/96325638-e7aee800-105b-11eb-9734-f97a5cfbe005.png)
![image](https://user-images.githubusercontent.com/17615663/96325647-f5646d80-105b-11eb-9444-bbc8cadb32d4.png)

**Comment by VectorHou** [comment]
s[x, y]的含义应该是[x, y)吧

**Comment by everyx** [comment]
已在 a0536710f34d693d0e78a53ec563426f0faa266f 修正
